# ██████╗ ██████╗ ███╗   ███╗███╗   ███╗ ██████╗ ███╗   ██╗
#██╔════╝██╔═══██╗████╗ ████║████╗ ████║██╔═══██╗████╗  ██║
#██║     ██║   ██║██╔████╔██║██╔████╔██║██║   ██║██╔██╗ ██║
#██║     ██║   ██║██║╚██╔╝██║██║╚██╔╝██║██║   ██║██║╚██╗██║
#╚██████╗╚██████╔╝██║ ╚═╝ ██║██║ ╚═╝ ██║╚██████╔╝██║ ╚████║
# ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
#
default_config:
config:
websocket_api:
system_health:
hassio:
esphome:
conversation:
map:
#cloud:
zeroconf:
ssdp:
updater:
  reporting: false
discovery:
  ignore:
    - sabnzbd
