- alias: System Travis Build Failed
  id: "53"
  trigger:
    - platform: state
      entity_id: sensor.phixion_home_assistantconfig_last_build_state
      from: "started"
      to: "failed"
  action:
    - service: notify.telegram
      data_template:
        title: ðŸ›‘ Travis build failed
        message: >
          https://travis-ci.org/github/phixion/Home-AssistantConfig/builds/{{ states('sensor.phixion_home_assistantconfig_last_build_id') }}
- alias: System Travis Build passed
  id: "54"
  trigger:
    - platform: state
      entity_id: sensor.phixion_home_assistantconfig_last_build_state
      from: "started"
      to: "passed"
  action:
    - service: notify.telegram
      data_template:
        title: âœ”ï¸ Travis build passed - restarting HomeAssistant
        message: >
          https://travis-ci.org/github/phixion/Home-AssistantConfig/builds/{{ states('sensor.phixion_home_assistantconfig_last_build_id') }}
    - service: homeassistant.restart