- alias: Notification Xur
  id: "19"
  trigger:
    - platform: state
      entity_id: sensor.where_the_fuck_is_xur
  action:
    - service: notify.telegram
      data_template:
        title: Xûr changed location
        message: "{{states('sensor.where_the_fuck_is_xur')}}"
    - service: notify.discord 
      data:
        message: "Xûr is at {{state_attr('sensor.where_the_fuck_is_xur', 'planet')}}, {{state_attr('sensor.where_the_fuck_is_xur', 'zone')}}, {{state_attr('sensor.where_the_fuck_is_xur', 'desc')}}"
        target: !secret discord_channel_id0
        data:
         images:
            - "c{{state_attr('sensor.where_the_fuck_is_xur', 'img')}}"
    - service: telegram_bot.send_photo
      data_template:
        target: "{{ trigger.event.data.user_id }}"
        disable_notification: true
        file: "{{state_attr('sensor.where_the_fuck_is_xur', 'img')}}"
#- alias: Update Xur Sensor
#  id: "17"
#  trigger:
#    - platform: time_pattern
#      minutes: /120
#  condition:
#    condition: time
#    after: "19:00:00"
#    weekday:
#      - fri
#      - sat
#      - sun
#      - mon
#  action:
#    - service: homeassistant.update_entity
#      entity_id: sensor.wtfisxur
