- alias: "Telegram Play frenck on TV"
  id: "41"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      command: "/yt_frenck"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Status"
    - service: homeassistant.toggle
      entity_id: input_boolean.play_frenck
- alias: Notification Frenck Video
  id: "14"
  trigger:
    - platform: state
      entity_id: sensor.franck_nijhof
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_frenck_video.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_frenck_video.attributes.last_triggered != none }}"
  action:
    - service: notify.telegram
      data_template:
        title: New Frenck Video
        message: >
          {{states('sensor.franck_nijhof')}}
           {{state_attr('sensor.franck_nijhof', 'url')}}
        data:
          inline_keyboard:
            - "Play Video on TV:/yt_frenck"
    - service: notify.lametric
      data:
        message: "Neues Frenck Video"
        data:
          sound: 'notification'
          icon: 'a10835'
          cycles: 10
          priority: 'critical'
- alias: "AndroidTV Play Latest Frenck Video"
  id: "33"
  trigger:
    platform: state
    entity_id: input_boolean.play_frenck
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.shield
      data_template:
        media_content_id: "{{state_attr('sensor.franck_nijhof', 'url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_frenck
