- alias: "Telegram Play Cheese Forever on TV"
  id: "411"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      command: "/yt_cheeseforever"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Status"
    - service: homeassistant.toggle
      entity_id: input_boolean.play_cheese_forever
- alias: Notification Cheese Forever Video
  id: "114"
  trigger:
    - platform: state
      entity_id: sensor.cheese_forever
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_cheese_forever_video.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_cheese_forever_video.attributes.last_triggered != none }}"
  action:
    - service: notify.telegram
      data_template:
        title: New Cheese Forever Video
        message: >
          {{states('sensor.cheese_forever')}}
           {{state_attr('sensor.cheese_forever', 'url')}}
        data:
          inline_keyboard:
            - "Play Video on TV:/yt_cheeseforever"
    - service: notify.lametric
      data:
        message: "Cheese Forever Video"
        data:
          sound: "notification"
          icon: "a10835"
          cycles: 0
          lifetime: 3600
          priority: "critical"
- alias: "AndroidTV Play Latest Cheese Forever"
  id: "133"
  trigger:
    platform: state
    entity_id: input_boolean.play_cheeseforever
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.shield
      data_template:
        media_content_id: "{{state_attr('sensor.cheese_forever', 'url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_cheeseforever
